package dev.harrison.rendacomcarro.operation.application;
import dev.harrison.rendacomcarro.operation.domain.*; import dev.harrison.rendacomcarro.operation.infrastructure.*; import dev.harrison.rendacomcarro.shared.domain.DomainConflictException; import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ShiftService {
 private final ShiftRepository shifts; private final PlatformRepository platforms; private final OperationalDayService days;
 public ShiftService(ShiftRepository shifts,PlatformRepository platforms,OperationalDayService days){this.shifts=shifts;this.platforms=platforms;this.days=days;}
 @Transactional public Shift openShift(UUID dayId,LocalDateTime start,BigDecimal odo,String region,Set<UUID> platformIds){OperationalDay day=days.get(dayId); if(day.getStatus()!=OperationalDayStatus.IN_PROGRESS) throw new DomainConflictException("Dia operacional não está em andamento"); if(shifts.existsByOperationalDayIdAndStatus(dayId,ShiftStatus.OPEN)) throw new DomainConflictException("Já existe turno aberto neste dia"); BigDecimal minimum=shifts.findFirstByOperationalDayIdOrderByStartedAtDesc(dayId).map(s->s.getFinalOdometer()==null?s.getInitialOdometer():s.getFinalOdometer()).orElse(day.getInitialOdometer()); if(odo==null||odo.compareTo(minimum)<0) throw new IllegalArgumentException("Odômetro inicial não pode ser menor que o último registro"); if(platformIds==null||platformIds.isEmpty()) throw new IllegalArgumentException("Selecione ao menos uma plataforma"); Set<Platform> selected=new LinkedHashSet<>(platforms.findAllById(platformIds)); if(selected.size()!=platformIds.size()) throw new IllegalArgumentException("Plataforma inválida"); return shifts.save(Shift.open(day,start,odo,region,selected));}
 @Transactional public Shift closeShift(UUID id,LocalDateTime end,BigDecimal odo,String region,Set<String> neighborhoods){Shift shift=get(id); shift.close(end,odo,region,neighborhoods); return shifts.save(shift);}
 @Transactional(readOnly=true) public Shift get(UUID id){return shifts.findById(id).orElseThrow(()->new IllegalArgumentException("Turno não encontrado"));}
 @Transactional(readOnly=true) public List<Shift> listByDay(UUID dayId){return shifts.findAllByOperationalDayIdOrderByStartedAtAsc(dayId);}
}
