package dev.harrison.rendacomcarro.operation.web;
import dev.harrison.rendacomcarro.operation.application.*; import dev.harrison.rendacomcarro.operation.domain.*; import dev.harrison.rendacomcarro.shared.domain.DomainConflictException; import dev.harrison.rendacomcarro.vehicle.application.VehicleService; import jakarta.validation.Valid; import java.math.BigDecimal; import java.time.LocalDate; import java.util.UUID; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller @RequestMapping("/operation-days")
public class OperationalDayController {
 private final OperationalDayService days; private final ShiftService shifts; private final VehicleService vehicles;
 public OperationalDayController(OperationalDayService days,ShiftService shifts,VehicleService vehicles){this.days=days;this.shifts=shifts;this.vehicles=vehicles;}
 @GetMapping public String list(Model model){model.addAttribute("days",days.listAll()); return "operation-days/list";}
 @GetMapping("/new") public String newForm(Model model){if(!model.containsAttribute("operationalDayForm")){OperationalDayForm form=new OperationalDayForm(); form.setDate(LocalDate.now()); try{var vehicle=vehicles.getPrimaryVehicle(); form.setVehicleId(vehicle.getId()); form.setInitialOdometer(vehicle.getCurrentOdometer());}catch(IllegalStateException ignored){} model.addAttribute("operationalDayForm",form);} model.addAttribute("vehicles",vehicles.listAll()); return "operation-days/form";}
 @PostMapping public String create(@Valid @ModelAttribute("operationalDayForm") OperationalDayForm form,BindingResult result,Model model,RedirectAttributes redirect){if(result.hasErrors()){model.addAttribute("vehicles",vehicles.listAll());return "operation-days/form";} try{OperationalDay day=days.openDay(form.getDate(),form.getVehicleId(),form.getPlannedGoal(),form.getInitialOdometer()); redirect.addFlashAttribute("successMessage","Dia operacional aberto."); return "redirect:/operation-days/"+day.getId();}catch(IllegalArgumentException|DomainConflictException ex){result.reject("operationDay",ex.getMessage());model.addAttribute("vehicles",vehicles.listAll());return "operation-days/form";}}
 @GetMapping("/{id}") public String detail(@PathVariable UUID id,Model model){model.addAttribute("day",days.get(id));model.addAttribute("shifts",shifts.listByDay(id));return "operation-days/detail";}
 @PostMapping("/{id}/close") public String close(@PathVariable UUID id,@RequestParam BigDecimal finalOdometer,RedirectAttributes redirect){try{days.closeDay(id,finalOdometer);redirect.addFlashAttribute("successMessage","Dia operacional fechado.");}catch(IllegalArgumentException|DomainConflictException ex){redirect.addFlashAttribute("errorMessage",ex.getMessage());}return "redirect:/operation-days/"+id;}
 @PostMapping("/{id}/cancel") public String cancel(@PathVariable UUID id,RedirectAttributes redirect){try{days.cancelDay(id);redirect.addFlashAttribute("successMessage","Dia operacional cancelado.");}catch(DomainConflictException ex){redirect.addFlashAttribute("errorMessage",ex.getMessage());}return "redirect:/operation-days/"+id;}
}
