package dev.harrison.rendacomcarro.operation.web;
import dev.harrison.rendacomcarro.operation.application.*; import dev.harrison.rendacomcarro.operation.infrastructure.PlatformRepository; import dev.harrison.rendacomcarro.shared.domain.DomainConflictException; import jakarta.validation.Valid; import java.time.LocalDateTime; import java.util.UUID; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller public class ShiftController {
 private final ShiftService shifts; private final OperationalDayService days; private final PlatformRepository platforms;
 public ShiftController(ShiftService shifts,OperationalDayService days,PlatformRepository platforms){this.shifts=shifts;this.days=days;this.platforms=platforms;}
 @GetMapping("/operation-days/{dayId}/shifts/new") public String openForm(@PathVariable UUID dayId,Model model){var day=days.get(dayId);if(!model.containsAttribute("openShiftForm")){OpenShiftForm form=new OpenShiftForm();form.setStartedAt(LocalDateTime.now().withSecond(0).withNano(0));var prior=shifts.listByDay(dayId);form.setInitialOdometer(prior.isEmpty()?day.getInitialOdometer():prior.get(prior.size()-1).getFinalOdometer());model.addAttribute("openShiftForm",form);}model.addAttribute("day",day);model.addAttribute("platforms",platforms.findAllByActiveTrueOrderByNameAsc());return "shifts/form";}
 @PostMapping("/operation-days/{dayId}/shifts") public String open(@PathVariable UUID dayId,@Valid @ModelAttribute("openShiftForm") OpenShiftForm form,BindingResult result,Model model,RedirectAttributes redirect){if(result.hasErrors()){model.addAttribute("day",days.get(dayId));model.addAttribute("platforms",platforms.findAllByActiveTrueOrderByNameAsc());return "shifts/form";}try{shifts.openShift(dayId,form.getStartedAt(),form.getInitialOdometer(),form.getStartRegion(),form.getPlatformIds());redirect.addFlashAttribute("successMessage","Turno iniciado.");return "redirect:/operation-days/"+dayId;}catch(IllegalArgumentException|DomainConflictException ex){result.reject("shift",ex.getMessage());model.addAttribute("day",days.get(dayId));model.addAttribute("platforms",platforms.findAllByActiveTrueOrderByNameAsc());return "shifts/form";}}
 @GetMapping("/shifts/{id}/close") public String closeForm(@PathVariable UUID id,Model model){var shift=shifts.get(id);if(!model.containsAttribute("closeShiftForm")){CloseShiftForm form=new CloseShiftForm();form.setEndedAt(LocalDateTime.now().withSecond(0).withNano(0));form.setFinalOdometer(shift.getInitialOdometer());model.addAttribute("closeShiftForm",form);}model.addAttribute("shift",shift);return "shifts/close";}
 @PostMapping("/shifts/{id}/close") public String close(@PathVariable UUID id,@Valid @ModelAttribute("closeShiftForm") CloseShiftForm form,BindingResult result,Model model,RedirectAttributes redirect){var shift=shifts.get(id);if(result.hasErrors()){model.addAttribute("shift",shift);return "shifts/close";}try{var closed=shifts.closeShift(id,form.getEndedAt(),form.getFinalOdometer(),form.getEndRegion(),form.neighborhoods());redirect.addFlashAttribute("successMessage","Turno encerrado.");return "redirect:/operation-days/"+closed.getOperationalDay().getId();}catch(IllegalArgumentException|DomainConflictException ex){result.reject("shift",ex.getMessage());model.addAttribute("shift",shift);return "shifts/close";}}
}
